### ISSUE TITLE
Implement Basic Lexer

### ISSUE THREAD

**Issue by Gipson62** [RedGear-Studio/atlas-core#48]
# Description
This issue is dedicated to implementing a basic lexer in atlas-core. The lexer should be able to tokenize simple expressions and numerical values.

# Tasks
- [x] Create a lexer module within atlas-core.
- [x] Develop tokenization functionality for simple expressions.
- [x] Implement tokenization for numerical values.
